package com.hrms.service;

import java.util.List;

import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import com.hrms.dto.EmployeeRequestDTO;
import com.hrms.dto.EmployeeResponseDTO;
import com.hrms.entity.Employee;
import com.hrms.repository.EmployeeRepository;
import lombok.RequiredArgsConstructor;


@Service
@RequiredArgsConstructor //Alternate to @Autowired
public class EmployeeServiceImpl implements EmployeeService {
    private final EmployeeRepository employeeRepository;
    private final PasswordEncoder passwordEncoder;
    private Employee mapToEntity(EmployeeRequestDTO dto){
        return Employee.builder().firstName(dto.getFirstName())
            .lastName(dto.getLastName())
            .email(dto.getEmail())
            .password(passwordEncoder.encode(dto.getPassword())) // Encoding password
            .department(dto.getDepartment())
            .role(dto.getRole())
            .phone(dto.getPhone())
            .salary(dto.getSalary())
            .joiningDate(dto.getJoiningDate())
            .status(dto.getStatus())
            .build();
    }

    private EmployeeResponseDTO mapToResponse (Employee employee){
        return EmployeeResponseDTO.builder()
            .id(employee.getId())
            .firstName(employee.getFirstName())
            .lastName(employee.getLastName())
            .email(employee.getEmail())
            .department(employee.getDepartment())
            .role(employee.getRole())
            .phone(employee.getPhone())
            .salary(employee.getSalary())
            .joiningDate(employee.getJoiningDate())
            .status(employee.getStatus())
            .build();
    }
    //CREATE
    @Override
    public EmployeeResponseDTO createEmployee(EmployeeRequestDTO dto){
        if(employeeRepository.existsByEmail(dto.getEmail())){
            throw new RuntimeException("Email already exists");
        }
       
        Employee employee= mapToEntity(dto);

        Employee savedEmployee = employeeRepository.save(employee);

        return mapToResponse(savedEmployee);

    };

    //READ
    @Override
    public List <EmployeeResponseDTO> getAllEmployees(){
        return employeeRepository.findAll().stream().map(this::mapToResponse).toList();
    }

    //READ By ID
    @Override
    public  EmployeeResponseDTO getEmployeeById(Long id){
        Employee employee= employeeRepository.findById(id).orElseThrow(()-> new RuntimeException("Employee not Found"));//can use .get() as well
        return mapToResponse(employee);
     }

     //UPDATE
     @Override
    public EmployeeResponseDTO updateEmployeeId(Long id, EmployeeRequestDTO dto){
       Employee employee = employeeRepository.findById(id).orElseThrow(()-> new RuntimeException("Employee Not Found"));
      employee.setFirstName(dto.getFirstName());
      employee.setLastName(dto.getLastName());
    employee.setDepartment(dto.getDepartment());
    employee.setPhone(dto.getPhone());
    employee.setSalary(dto.getSalary());
    employee.setStatus(dto.getStatus());

    Employee updatedEmployee = employeeRepository.save(employee);
    return mapToResponse(updatedEmployee);

}

//DELETE
@Override
 public void deleteEmployee(Long id){
    Employee employee = employeeRepository.findById(id).orElseThrow(()-> new RuntimeException("Employee Not Found"));

    employeeRepository.delete(employee);

 }

    //PROFILE
    @Override
    public EmployeeResponseDTO getProfile(String email){
        Employee employee = employeeRepository.findByEmail(email).orElseThrow(()-> new RuntimeException("Employee Not Found"));
        return mapToResponse(employee);
    }
        
    }


/*
*The .builder() method activates the Builder Design Pattern generated by Lombok's @Builder annotation.It acts as a factory method that creates a temporary helper object (called a "builder").
 You use this helper object to configure your main object step-by-step using method chaining before finally creating it.
* Employee emp = Employee.builder()           // 1. Creates the builder helper object
                       .firstName("John")   // 2. Sets the firstName field
                       .lastName("Doe")     // 3. Sets the lastName field
                       .build();            // 4. Instantiates the final Employee object

*/

/*
1. @OverrideThis annotation tells the compiler that this method is overriding a method declared in a parent interface (likely an EmployeeService interface). It prevents typos in the method name.2. public List<EmployeeResponseDTO> getAllEmployees() {public: Accessible from any other class (like your Controller).List<EmployeeResponseDTO>: The return type. Instead of exposing raw database entities to the frontend, it returns a filtered, secure list of DTO objects.3. return employeeRepository.findAll()Calls your Spring Data JPA repository. This goes to the database, executes a SELECT * FROM employee; query under the hood, and returns a standard List<Employee>.4. .stream()Converts that standard List<Employee> into a Stream of Employees. Think of a Stream as a conveyor belt where employee objects flow one by one, allowing you to perform operations on them sequentially.5. .map(this::mapToResponse)This is the transformation step..map(...): Takes each item on the conveyor belt and changes it into something else.this::mapToResponse: This is a Method Reference. It tells the stream to pass each Employee object into a helper method named mapToResponse that exists inside this same class (this). That helper method converts an Employee entity into an EmployeeResponseDTO.6. .toList();Closes the stream pipeline. It collects all the newly transformed EmployeeResponseDTO objects off the conveyor belt and packages them back into a regular, immutable List<EmployeeResponseDTO>.
*/